// 常见姓氏库
export const SURNAMES = [
  { chinese: '李', pinyin: 'Li', frequency: 100 },
  { chinese: '王', pinyin: 'Wang', frequency: 95 },
  { chinese: '张', pinyin: 'Zhang', frequency: 90 },
  { chinese: '刘', pinyin: 'Liu', frequency: 85 },
  { chinese: '陈', pinyin: 'Chen', frequency: 80 },
  { chinese: '杨', pinyin: 'Yang', frequency: 75 },
  { chinese: '黄', pinyin: 'Huang', frequency: 70 },
  { chinese: '赵', pinyin: 'Zhao', frequency: 65 },
  { chinese: '吴', pinyin: 'Wu', frequency: 60 },
  { chinese: '周', pinyin: 'Zhou', frequency: 55 },
  { chinese: '徐', pinyin: 'Xu', frequency: 50 },
  { chinese: '孙', pinyin: 'Sun', frequency: 48 },
  { chinese: '马', pinyin: 'Ma', frequency: 46 },
  { chinese: '朱', pinyin: 'Zhu', frequency: 44 },
  { chinese: '胡', pinyin: 'Hu', frequency: 42 },
  { chinese: '郭', pinyin: 'Guo', frequency: 40 },
  { chinese: '林', pinyin: 'Lin', frequency: 38 },
  { chinese: '何', pinyin: 'He', frequency: 36 },
  { chinese: '高', pinyin: 'Gao', frequency: 34 },
  { chinese: '罗', pinyin: 'Luo', frequency: 32 },
  { chinese: '郑', pinyin: 'Zheng', frequency: 30 },
  { chinese: '梁', pinyin: 'Liang', frequency: 28 },
  { chinese: '谢', pinyin: 'Xie', frequency: 26 },
  { chinese: '宋', pinyin: 'Song', frequency: 24 },
  { chinese: '唐', pinyin: 'Tang', frequency: 22 },
  { chinese: '许', pinyin: 'Xu', frequency: 20 },
  { chinese: '韩', pinyin: 'Han', frequency: 19 },
  { chinese: '冯', pinyin: 'Feng', frequency: 18 },
  { chinese: '邓', pinyin: 'Deng', frequency: 17 },
  { chinese: '曹', pinyin: 'Cao', frequency: 16 },
  { chinese: '彭', pinyin: 'Peng', frequency: 15 },
  { chinese: '曾', pinyin: 'Zeng', frequency: 14 },
  { chinese: '肖', pinyin: 'Xiao', frequency: 13 },
  { chinese: '田', pinyin: 'Tian', frequency: 12 },
  { chinese: '董', pinyin: 'Dong', frequency: 11 },
  { chinese: '袁', pinyin: 'Yuan', frequency: 10 },
  { chinese: '潘', pinyin: 'Pan', frequency: 9 },
  { chinese: '于', pinyin: 'Yu', frequency: 8 },
  { chinese: '蒋', pinyin: 'Jiang', frequency: 7 },
  { chinese: '蔡', pinyin: 'Cai', frequency: 6 },
  { chinese: '余', pinyin: 'Yu', frequency: 5 },
  { chinese: '杜', pinyin: 'Du', frequency: 4 },
  { chinese: '叶', pinyin: 'Ye', frequency: 3 },
  { chinese: '程', pinyin: 'Cheng', frequency: 2 },
  { chinese: '苏', pinyin: 'Su', frequency: 1 },
  { chinese: '魏', pinyin: 'Wei', frequency: 1 },
  { chinese: '吕', pinyin: 'Lv', frequency: 1 },
  { chinese: '丁', pinyin: 'Ding', frequency: 1 },
  { chinese: '任', pinyin: 'Ren', frequency: 1 },
  { chinese: '沈', pinyin: 'Shen', frequency: 1 },
];

// 名字字库（按风格分类）
export const NAME_CHARACTERS = {
  classic: {
    male: [
      { char: '文', pinyin: 'wen', strokes: 4, meaning: 'cultured, literary' },
      { char: '武', pinyin: 'wu', strokes: 8, meaning: 'martial, brave' },
      { char: '明', pinyin: 'ming', strokes: 8, meaning: 'bright, clear' },
      { char: '德', pinyin: 'de', strokes: 15, meaning: 'virtue, morality' },
      { char: '仁', pinyin: 'ren', strokes: 4, meaning: 'benevolence, kindness' },
      { char: '义', pinyin: 'yi', strokes: 3, meaning: 'righteousness, justice' },
      { char: '礼', pinyin: 'li', strokes: 5, meaning: 'courtesy, etiquette' },
      { char: '智', pinyin: 'zhi', strokes: 12, meaning: 'wisdom, intelligence' },
      { char: '信', pinyin: 'xin', strokes: 9, meaning: 'trust, honesty' },
      { char: '忠', pinyin: 'zhong', strokes: 8, meaning: 'loyalty, devotion' },
      { char: '孝', pinyin: 'xiao', strokes: 7, meaning: 'filial piety' },
      { char: '勇', pinyin: 'yong', strokes: 9, meaning: 'courage, bravery' },
      { char: '正', pinyin: 'zheng', strokes: 5, meaning: 'upright, righteous' },
      { char: '诚', pinyin: 'cheng', strokes: 8, meaning: 'sincere, honest' },
      { char: '谦', pinyin: 'qian', strokes: 12, meaning: 'modest, humble' },
      { char: '和', pinyin: 'he', strokes: 8, meaning: 'harmony, peace' },
      { char: '善', pinyin: 'shan', strokes: 12, meaning: 'good, kind' },
      { char: '恭', pinyin: 'gong', strokes: 10, meaning: 'respectful, polite' },
      { char: '廉', pinyin: 'lian', strokes: 13, meaning: 'honest, incorruptible' },
      { char: '毅', pinyin: 'yi', strokes: 15, meaning: 'resolute, determined' },
      { char: '刚', pinyin: 'gang', strokes: 6, meaning: 'firm, strong' },
      { char: '直', pinyin: 'zhi', strokes: 8, meaning: 'straight, upright' },
      { char: '朴', pinyin: 'pu', strokes: 6, meaning: 'simple, plain' },
      { char: '厚', pinyin: 'hou', strokes: 9, meaning: 'generous, kind' },
      { char: '敬', pinyin: 'jing', strokes: 12, meaning: 'respect, honor' },
    ],
    female: [
      { char: '雅', pinyin: 'ya', strokes: 12, meaning: 'elegant, graceful' },
      { char: '静', pinyin: 'jing', strokes: 14, meaning: 'quiet, calm' },
      { char: '婉', pinyin: 'wan', strokes: 11, meaning: 'graceful, gentle' },
      { char: '淑', pinyin: 'shu', strokes: 11, meaning: 'virtuous, kind' },
      { char: '慧', pinyin: 'hui', strokes: 15, meaning: 'intelligent, wise' },
      { char: '贤', pinyin: 'xian', strokes: 8, meaning: 'virtuous, worthy' },
      { char: '娴', pinyin: 'xian', strokes: 10, meaning: 'refined, elegant' },
      { char: '柔', pinyin: 'rou', strokes: 9, meaning: 'gentle, soft' },
      { char: '端', pinyin: 'duan', strokes: 14, meaning: 'proper, dignified' },
      { char: '贞', pinyin: 'zhen', strokes: 6, meaning: 'chaste, loyal' },
      { char: '惠', pinyin: 'hui', strokes: 12, meaning: 'kind, benevolent' },
      { char: '温', pinyin: 'wen', strokes: 12, meaning: 'warm, gentle' },
      { char: '敏', pinyin: 'min', strokes: 11, meaning: 'quick, clever' },
      { char: '秀', pinyin: 'xiu', strokes: 7, meaning: 'elegant, beautiful' },
      { char: '芳', pinyin: 'fang', strokes: 7, meaning: 'fragrant, virtuous' },
      { char: '清', pinyin: 'qing', strokes: 11, meaning: 'clear, pure' },
      { char: '素', pinyin: 'su', strokes: 10, meaning: 'plain, simple' },
      { char: '真', pinyin: 'zhen', strokes: 10, meaning: 'true, genuine' },
      { char: '纯', pinyin: 'chun', strokes: 7, meaning: 'pure, innocent' },
      { char: '洁', pinyin: 'jie', strokes: 9, meaning: 'clean, pure' },
      { char: '贤', pinyin: 'xian', strokes: 8, meaning: 'virtuous, worthy' },
      { char: '淳', pinyin: 'chun', strokes: 11, meaning: 'honest, sincere' },
      { char: '娟', pinyin: 'juan', strokes: 10, meaning: 'beautiful, graceful' },
      { char: '仪', pinyin: 'yi', strokes: 5, meaning: 'ceremony, appearance' },
      { char: '容', pinyin: 'rong', strokes: 10, meaning: 'appearance, tolerance' },
    ],
  },
  modern: {
    male: [
      { char: '轩', pinyin: 'xuan', strokes: 10, meaning: 'high, lofty' },
      { char: '宇', pinyin: 'yu', strokes: 6, meaning: 'universe, space' },
      { char: '晨', pinyin: 'chen', strokes: 11, meaning: 'morning, dawn' },
      { char: '睿', pinyin: 'rui', strokes: 14, meaning: 'wise, intelligent' },
      { char: '泽', pinyin: 'ze', strokes: 8, meaning: 'grace, favor' },
      { char: '博', pinyin: 'bo', strokes: 12, meaning: 'broad, extensive' },
      { char: '翔', pinyin: 'xiang', strokes: 12, meaning: 'soar, fly' },
      { char: '昊', pinyin: 'hao', strokes: 8, meaning: 'vast sky' },
      { char: '煜', pinyin: 'yu', strokes: 13, meaning: 'bright, shining' },
      { char: '皓', pinyin: 'hao', strokes: 12, meaning: 'bright, luminous' },
      { char: '辰', pinyin: 'chen', strokes: 7, meaning: 'time, stars' },
      { char: '骏', pinyin: 'jun', strokes: 10, meaning: 'excellent horse' },
      { char: '鹏', pinyin: 'peng', strokes: 13, meaning: 'giant bird' },
      { char: '浩', pinyin: 'hao', strokes: 10, meaning: 'vast, grand' },
      { char: '俊', pinyin: 'jun', strokes: 9, meaning: 'handsome, talented' },
    ],
    female: [
      { char: '欣', pinyin: 'xin', strokes: 8, meaning: 'happy, joyful' },
      { char: '悦', pinyin: 'yue', strokes: 10, meaning: 'pleased, delighted' },
      { char: '琪', pinyin: 'qi', strokes: 12, meaning: 'precious jade' },
      { char: '萱', pinyin: 'xuan', strokes: 12, meaning: 'day lily flower' },
      { char: '涵', pinyin: 'han', strokes: 11, meaning: 'contain, cultivate' },
      { char: '瑶', pinyin: 'yao', strokes: 14, meaning: 'precious jade' },
      { char: '璐', pinyin: 'lu', strokes: 17, meaning: 'beautiful jade' },
      { char: '薇', pinyin: 'wei', strokes: 16, meaning: 'fern, elegant' },
      { char: '晴', pinyin: 'qing', strokes: 12, meaning: 'clear, sunny' },
      { char: '诺', pinyin: 'nuo', strokes: 10, meaning: 'promise, consent' },
      { char: '曦', pinyin: 'xi', strokes: 20, meaning: 'morning sunlight' },
      { char: '澜', pinyin: 'lan', strokes: 15, meaning: 'waves, ripples' },
      { char: '彤', pinyin: 'tong', strokes: 7, meaning: 'red, vibrant' },
      { char: '婷', pinyin: 'ting', strokes: 12, meaning: 'graceful, pretty' },
      { char: '妍', pinyin: 'yan', strokes: 7, meaning: 'beautiful, elegant' },
    ],
  },
  nature: {
    male: [
      { char: '林', pinyin: 'lin', strokes: 8, meaning: 'forest, woods' },
      { char: '山', pinyin: 'shan', strokes: 3, meaning: 'mountain' },
      { char: '海', pinyin: 'hai', strokes: 10, meaning: 'ocean, sea' },
      { char: '松', pinyin: 'song', strokes: 8, meaning: 'pine tree' },
      { char: '云', pinyin: 'yun', strokes: 4, meaning: 'cloud' },
      { char: '峰', pinyin: 'feng', strokes: 10, meaning: 'peak, summit' },
      { char: '川', pinyin: 'chuan', strokes: 3, meaning: 'river, stream' },
      { char: '泉', pinyin: 'quan', strokes: 9, meaning: 'spring, fountain' },
      { char: '石', pinyin: 'shi', strokes: 5, meaning: 'stone, rock' },
      { char: '枫', pinyin: 'feng', strokes: 8, meaning: 'maple tree' },
      { char: '柏', pinyin: 'bai', strokes: 9, meaning: 'cypress tree' },
      { char: '江', pinyin: 'jiang', strokes: 6, meaning: 'river' },
      { char: '涛', pinyin: 'tao', strokes: 10, meaning: 'waves, billows' },
      { char: '岩', pinyin: 'yan', strokes: 8, meaning: 'cliff, rock' },
      { char: '森', pinyin: 'sen', strokes: 12, meaning: 'forest, dense' },
    ],
    female: [
      { char: '梅', pinyin: 'mei', strokes: 11, meaning: 'plum blossom' },
      { char: '兰', pinyin: 'lan', strokes: 5, meaning: 'orchid' },
      { char: '竹', pinyin: 'zhu', strokes: 6, meaning: 'bamboo' },
      { char: '菊', pinyin: 'ju', strokes: 11, meaning: 'chrysanthemum' },
      { char: '莲', pinyin: 'lian', strokes: 10, meaning: 'lotus' },
      { char: '荷', pinyin: 'he', strokes: 10, meaning: 'lotus, water lily' },
      { char: '桃', pinyin: 'tao', strokes: 10, meaning: 'peach blossom' },
      { char: '柳', pinyin: 'liu', strokes: 9, meaning: 'willow tree' },
      { char: '蕊', pinyin: 'rui', strokes: 15, meaning: 'flower stamen' },
      { char: '茉', pinyin: 'mo', strokes: 8, meaning: 'jasmine' },
      { char: '樱', pinyin: 'ying', strokes: 15, meaning: 'cherry blossom' },
      { char: '蓉', pinyin: 'rong', strokes: 13, meaning: 'hibiscus' },
      { char: '芷', pinyin: 'zhi', strokes: 7, meaning: 'angelica herb' },
      { char: '茜', pinyin: 'qian', strokes: 9, meaning: 'madder plant' },
      { char: '芸', pinyin: 'yun', strokes: 7, meaning: 'rue herb' },
    ],
  },
  poetic: {
    male: [
      { char: '诗', pinyin: 'shi', strokes: 8, meaning: 'poetry, poem' },
      { char: '韵', pinyin: 'yun', strokes: 13, meaning: 'rhyme, charm' },
      { char: '墨', pinyin: 'mo', strokes: 15, meaning: 'ink, literary' },
      { char: '书', pinyin: 'shu', strokes: 4, meaning: 'book, writing' },
      { char: '逸', pinyin: 'yi', strokes: 11, meaning: 'ease, leisure' },
      { char: '风', pinyin: 'feng', strokes: 4, meaning: 'wind, style' },
      { char: '月', pinyin: 'yue', strokes: 4, meaning: 'moon' },
      { char: '星', pinyin: 'xing', strokes: 9, meaning: 'star' },
      { char: '霖', pinyin: 'lin', strokes: 16, meaning: 'continuous rain' },
      { char: '澈', pinyin: 'che', strokes: 15, meaning: 'clear, pure' },
      { char: '溪', pinyin: 'xi', strokes: 13, meaning: 'stream, brook' },
      { char: '舟', pinyin: 'zhou', strokes: 6, meaning: 'boat' },
      { char: '帆', pinyin: 'fan', strokes: 6, meaning: 'sail' },
      { char: '弦', pinyin: 'xian', strokes: 8, meaning: 'string, chord' },
      { char: '笛', pinyin: 'di', strokes: 11, meaning: 'flute' },
    ],
    female: [
      { char: '诗', pinyin: 'shi', strokes: 8, meaning: 'poetry, poem' },
      { char: '画', pinyin: 'hua', strokes: 8, meaning: 'painting, picture' },
      { char: '琴', pinyin: 'qin', strokes: 12, meaning: 'musical instrument' },
      { char: '韵', pinyin: 'yun', strokes: 13, meaning: 'rhyme, charm' },
      { char: '雨', pinyin: 'yu', strokes: 8, meaning: 'rain' },
      { char: '霜', pinyin: 'shuang', strokes: 17, meaning: 'frost' },
      { char: '雪', pinyin: 'xue', strokes: 11, meaning: 'snow' },
      { char: '露', pinyin: 'lu', strokes: 20, meaning: 'dew' },
      { char: '烟', pinyin: 'yan', strokes: 10, meaning: 'mist, smoke' },
      { char: '梦', pinyin: 'meng', strokes: 11, meaning: 'dream' },
      { char: '影', pinyin: 'ying', strokes: 15, meaning: 'shadow, reflection' },
      { char: '舞', pinyin: 'wu', strokes: 14, meaning: 'dance' },
      { char: '歌', pinyin: 'ge', strokes: 14, meaning: 'song' },
      { char: '筝', pinyin: 'zheng', strokes: 12, meaning: 'zither' },
      { char: '箫', pinyin: 'xiao', strokes: 14, meaning: 'vertical flute' },
    ],
  },
  lucky: {
    male: [
      { char: '福', pinyin: 'fu', strokes: 13, meaning: 'fortune, blessing' },
      { char: '瑞', pinyin: 'rui', strokes: 13, meaning: 'auspicious, lucky' },
      { char: '祥', pinyin: 'xiang', strokes: 10, meaning: 'auspicious, good omen' },
      { char: '吉', pinyin: 'ji', strokes: 6, meaning: 'lucky, auspicious' },
      { char: '昌', pinyin: 'chang', strokes: 8, meaning: 'prosperous, flourishing' },
      { char: '隆', pinyin: 'long', strokes: 11, meaning: 'prosperous, grand' },
      { char: '兴', pinyin: 'xing', strokes: 6, meaning: 'prosper, thrive' },
      { char: '荣', pinyin: 'rong', strokes: 9, meaning: 'glory, honor' },
      { char: '贵', pinyin: 'gui', strokes: 9, meaning: 'noble, precious' },
      { char: '富', pinyin: 'fu', strokes: 12, meaning: 'wealthy, abundant' },
      { char: '康', pinyin: 'kang', strokes: 11, meaning: 'healthy, peaceful' },
      { char: '安', pinyin: 'an', strokes: 6, meaning: 'peaceful, safe' },
      { char: '顺', pinyin: 'shun', strokes: 9, meaning: 'smooth, favorable' },
      { char: '泰', pinyin: 'tai', strokes: 10, meaning: 'peaceful, safe' },
      { char: '祺', pinyin: 'qi', strokes: 12, meaning: 'auspicious, lucky' },
    ],
    female: [
      { char: '瑞', pinyin: 'rui', strokes: 13, meaning: 'auspicious, lucky' },
      { char: '祥', pinyin: 'xiang', strokes: 10, meaning: 'auspicious, good omen' },
      { char: '喜', pinyin: 'xi', strokes: 12, meaning: 'joy, happiness' },
      { char: '福', pinyin: 'fu', strokes: 13, meaning: 'fortune, blessing' },
      { char: '宝', pinyin: 'bao', strokes: 8, meaning: 'treasure, precious' },
      { char: '珍', pinyin: 'zhen', strokes: 9, meaning: 'precious, rare' },
      { char: '瑾', pinyin: 'jin', strokes: 15, meaning: 'beautiful jade' },
      { char: '琳', pinyin: 'lin', strokes: 12, meaning: 'beautiful jade' },
      { char: '嘉', pinyin: 'jia', strokes: 14, meaning: 'excellent, auspicious' },
      { char: '怡', pinyin: 'yi', strokes: 8, meaning: 'happy, joyful' },
      { char: '乐', pinyin: 'le', strokes: 5, meaning: 'happy, joyful' },
      { char: '欢', pinyin: 'huan', strokes: 6, meaning: 'joyful, happy' },
      { char: '颜', pinyin: 'yan', strokes: 15, meaning: 'face, countenance' },
      { char: '锦', pinyin: 'jin', strokes: 13, meaning: 'brocade, splendid' },
      { char: '绣', pinyin: 'xiu', strokes: 10, meaning: 'embroidery, elegant' },
    ],
  },
  commercial: {
    male: [
      { char: '凯', pinyin: 'kai', strokes: 8, meaning: 'triumph, victory' },
      { char: '杰', pinyin: 'jie', strokes: 8, meaning: 'outstanding, hero' },
      { char: '强', pinyin: 'qiang', strokes: 11, meaning: 'strong, powerful' },
      { char: '伟', pinyin: 'wei', strokes: 6, meaning: 'great, mighty' },
      { char: '达', pinyin: 'da', strokes: 6, meaning: 'achieve, reach' },
      { char: '成', pinyin: 'cheng', strokes: 6, meaning: 'succeed, accomplish' },
      { char: '胜', pinyin: 'sheng', strokes: 9, meaning: 'victory, win' },
      { char: '卓', pinyin: 'zhuo', strokes: 8, meaning: 'outstanding, eminent' },
      { char: '越', pinyin: 'yue', strokes: 12, meaning: 'surpass, exceed' },
      { char: '超', pinyin: 'chao', strokes: 12, meaning: 'surpass, transcend' },
      { char: '锐', pinyin: 'rui', strokes: 12, meaning: 'sharp, keen' },
      { char: '进', pinyin: 'jin', strokes: 7, meaning: 'advance, progress' },
      { char: '展', pinyin: 'zhan', strokes: 10, meaning: 'expand, develop' },
      { char: '腾', pinyin: 'teng', strokes: 13, meaning: 'soar, rise' },
      { char: '飞', pinyin: 'fei', strokes: 3, meaning: 'fly, soar' },
    ],
    female: [
      { char: '敏', pinyin: 'min', strokes: 11, meaning: 'quick, clever' },
      { char: '慧', pinyin: 'hui', strokes: 15, meaning: 'intelligent, wise' },
      { char: '颖', pinyin: 'ying', strokes: 13, meaning: 'intelligent, bright' },
      { char: '佳', pinyin: 'jia', strokes: 8, meaning: 'excellent, beautiful' },
      { char: '丽', pinyin: 'li', strokes: 7, meaning: 'beautiful, pretty' },
      { char: '洁', pinyin: 'jie', strokes: 9, meaning: 'clean, pure' },
      { char: '雯', pinyin: 'wen', strokes: 12, meaning: 'cloud patterns' },
      { char: '娜', pinyin: 'na', strokes: 9, meaning: 'graceful, elegant' },
      { char: '莉', pinyin: 'li', strokes: 10, meaning: 'jasmine' },
      { char: '娟', pinyin: 'juan', strokes: 10, meaning: 'beautiful, graceful' },
      { char: '芬', pinyin: 'fen', strokes: 7, meaning: 'fragrance, aroma' },
      { char: '玲', pinyin: 'ling', strokes: 9, meaning: 'tinkling of jade' },
      { char: '珊', pinyin: 'shan', strokes: 9, meaning: 'coral' },
      { char: '倩', pinyin: 'qian', strokes: 10, meaning: 'beautiful, charming' },
      { char: '君', pinyin: 'jun', strokes: 7, meaning: 'noble, gentleman' },
    ],
  },
};

// 吉祥语库
export const LUCKY_PHRASES = [
  'May your name bring you endless fortune and happiness',
  'A name that shines like the morning sun',
  'Blessed with wisdom and prosperity',
  'Your name carries the spirit of success',
  'May this name guide you to greatness',
];
